package com.example.springjwt.models;

import java.util.ArrayList;
import java.util.List;

public enum ECryptocurrency {

    // These are all the cryptocurrencies that are supported by the application
    // This list contains the top 1000 cryptocurrencies ranked by market capitalization data from Coingecko on October 13th, 2022
    BITCOIN("bitcoin", "btc", "Bitcoin"),
    ETHEREUM("ethereum", "eth", "Ethereum"),
    TETHER("tether", "usdt", "Tether"),
    USD_COIN("usd-coin", "usdc", "USD Coin"),
    BNB("binancecoin", "bnb", "BNB"),
    XRP("ripple", "xrp", "XRP"),
    BINANCE_USD("binance-usd", "busd", "Binance USD"),
    CARDANO("cardano", "ada", "Cardano"),
    SOLANA("solana", "sol", "Solana"),
    DOGECOIN("dogecoin", "doge", "Dogecoin"),
    POLKADOT("polkadot", "dot", "Polkadot"),
    DAI("dai", "dai", "Dai"),
    SHIBA_INU("shiba-inu", "shib", "Shiba Inu"),
    POLYGON("matic-network", "matic", "Polygon"),
    TRON("tron", "trx", "TRON"),
    LIDO_STAKED_ETHER("staked-ether", "steth", "Lido Staked Ether"),
    WRAPPED_BITCOIN("wrapped-bitcoin", "wbtc", "Wrapped Bitcoin"),
    AVALANCHE("avalanche-2", "avax", "Avalanche"),
    UNISWAP("uniswap", "uni", "Uniswap"),
    OKB("okb", "okb", "OKB"),
    LEO_TOKEN("leo-token", "leo", "LEO Token"),
    LITECOIN("litecoin", "ltc", "Litecoin"),
    CHAINLINK("chainlink", "link", "Chainlink"),
    COSMOS_HUB("cosmos", "atom", "Cosmos Hub"),
    ETHEREUM_CLASSIC("ethereum-classic", "etc", "Ethereum Classic"),
    FTX("ftx-token", "ftt", "FTX"),
    STELLAR("stellar", "xlm", "Stellar"),
    MONERO("monero", "xmr", "Monero"),
    CRONOS("crypto-com-chain", "cro", "Cronos"),
    NEAR_PROTOCOL("near", "near", "NEAR Protocol"),
    ALGORAND("algorand", "algo", "Algorand"),
    BITCOIN_CASH("bitcoin-cash", "bch", "Bitcoin Cash"),
    QUANT("quant-network", "qnt", "Quant"),
    TERRA_LUNA_CLASSIC("terra-luna", "lunc", "Terra Luna Classic"),
    VECHAIN("vechain", "vet", "VeChain"),
    FLOW("flow", "flow", "Flow"),
    HEDERA("hedera-hashgraph", "hbar", "Hedera"),
    CHAIN("chain-2", "xcn", "Chain"),
    FILECOIN("filecoin", "fil", "Filecoin"),
    APECOIN("apecoin", "ape", "ApeCoin"),
    FRAX("frax", "frax", "Frax"),
    INTERNET_COMPUTER("internet-computer", "icp", "Internet Computer"),
    ELROND("elrond-erd-2", "egld", "Elrond"),
    TEZOS("tezos", "xtz", "Tezos"),
    AXIE_INFINITY("axie-infinity", "axs", "Axie Infinity"),
    DECENTRALAND("decentraland", "mana", "Decentraland"),
    THE_SANDBOX("the-sandbox", "sand", "The Sandbox"),
    EOS("eos", "eos", "EOS"),
    THETA_NETWORK("theta-token", "theta", "Theta Network"),
    CHILIZ("chiliz", "chz", "Chiliz"),
    AAVE("aave", "aave", "Aave"),
    BITCOIN_SV("bitcoin-cash-sv", "bsv", "Bitcoin SV"),
    HUOBI("huobi-token", "ht", "Huobi"),
    CUSDC("compound-usd-coin", "cusdc", "cUSDC"),
    TOKENIZE_XCHANGE("tokenize-xchange", "tkx", "Tokenize Xchange"),
    PAX_DOLLAR("paxos-standard", "usdp", "Pax Dollar"),
    TRUEUSD("true-usd", "tusd", "TrueUSD"),
    KUCOIN("kucoin-shares", "kcs", "KuCoin"),
    MAKER("maker", "mkr", "Maker"),
    LIDO_DAO("lido-dao", "ldo", "Lido DAO"),
    ETHEREUMPOW("ethereum-pow-iou", "ethw", "EthereumPoW"),
    USDD("usdd", "usdd", "USDD"),
    BITTORRENT("bittorrent", "btt", "BitTorrent"),
    ECASH("ecash", "xec", "eCash"),
    IOTA("iota", "miota", "IOTA"),
    ZCASH("zcash", "zec", "Zcash"),
    GATE("gatechain-token", "gt", "Gate"),
    THE_GRAPH("the-graph", "grt", "The Graph"),
    CDAI("cdai", "cdai", "cDAI"),
    PANCAKESWAP("pancakeswap-token", "cake", "PancakeSwap"),
    HELIUM("helium", "hnt", "Helium"),
    NEO("neo", "neo", "NEO"),
    RADIX("radix", "xrd", "Radix"),
    CETH("compound-ether", "ceth", "cETH"),
    FANTOM("fantom", "ftm", "Fantom"),
    PAX_GOLD("pax-gold", "paxg", "PAX Gold"),
    OSMOSIS("osmosis", "osmo", "Osmosis"),
    KLAYTN("klay-token", "klay", "Klaytn"),
    SYNTHETIX_NETWORK("havven", "snx", "Synthetix Network"),
    BITDAO("bitdao", "bit", "BitDAO"),
    NEXO("nexo", "nexo", "NEXO"),
    EVMOS("evmos", "evmos", "Evmos"),
    ZILLIQA("zilliqa", "zil", "Zilliqa"),
    TERRA("terra-luna-2", "luna", "Terra"),
    DASH("dash", "dash", "Dash"),
    ARWEAVE("arweave", "ar", "Arweave"),
    TERRACLASSICUSD("terrausd", "ustc", "TerraClassicUSD"),
    THORCHAIN("thorchain", "rune", "THORChain"),
    ETHEREUM_NAME_SERVICE("ethereum-name-service", "ens", "Ethereum Name Service"),
    XDC_NETWORK("xdce-crowd-sale", "xdc", "XDC Network"),
    KAVA("kava", "kava", "Kava"),
    ENJIN_COIN("enjincoin", "enj", "Enjin Coin"),
    BASIC_ATTENTION("basic-attention-token", "bat", "Basic Attention"),
    TETHER_GOLD("tether-gold", "xaut", "Tether Gold"),
    ROCKET_POOL("rocket-pool", "rpl", "Rocket Pool"),
    STACKS("blockstack", "stx", "Stacks"),
    CELSIUS_NETWORK("celsius-degree-token", "cel", "Celsius Network"),
    CONVEX_FINANCE("convex-finance", "cvx", "Convex Finance"),
    TRUST_WALLET("trust-wallet-token", "twt", "Trust Wallet"),
    DEFICHAIN("defichain", "dfi", "DeFiChain"),
    CASPER_NETWORK("casper-network", "cspr", "Casper Network"),
    MINA_PROTOCOL("mina-protocol", "mina", "Mina Protocol"),
    CUSDT("compound-usdt", "cusdt", "cUSDT"),
    COMPOUND("compound-governance-token", "comp", "Compound"),
    RAVENCOIN("ravencoin", "rvn", "Ravencoin"),
    AMP("amp-token", "amp", "Amp"),
    IMMUTABLE_X("immutable-x", "imx", "Immutable X"),
    STEPN("stepn", "gmt", "STEPN"),
    DECRED("decred", "dcr", "Decred"),
    BITCOIN_GOLD("bitcoin-gold", "btg", "Bitcoin Gold"),
    HOLO("holotoken", "hot", "Holo"),
    KUSAMA("kusama", "ksm", "Kusama"),
    ONE_INCH("1inch", "1inch", "1inch"),
    NEM("nem", "xem", "NEM"),
    ECOMI("ecomi", "omi", "ECOMI"),
    CELO("celo", "celo", "Celo"),
    WAVES("waves", "waves", "Waves"),
    MAIAR_DEX("maiar-dex", "mex", "Maiar DEX"),
    FRAX_SHARE("frax-share", "fxs", "Frax Share"),
    LOOPRING("loopring", "lrc", "Loopring"),
    GEMINI_DOLLAR("gemini-dollar", "gusd", "Gemini Dollar"),
    CURVE_DAO("curve-dao-token", "crv", "Curve DAO"),
    GMX("gmx", "gmx", "GMX"),
    OLYMPUS("olympus", "ohm", "Olympus"),
    GALA("gala", "gala", "Gala"),
    NEXUS_MUTUAL("nxm", "nxm", "Nexus Mutual"),
    THETA_FUEL("theta-fuel", "tfuel", "Theta Fuel"),
    GNOSIS("gnosis", "gno", "Gnosis"),
    RESERVE_RIGHTS("reserve-rights-token", "rsr", "Reserve Rights"),
    SAFEMOON_OLD("safemoon", "safemoon", "SafeMoon [OLD]"),
    QTUM("qtum", "qtum", "Qtum"),
    OASIS_NETWORK("oasis-network", "rose", "Oasis Network"),
    SERUM("serum", "srm", "Serum"),
    IOST("iostoken", "iost", "IOST"),
    KADENA("kadena", "kda", "Kadena"),
    HUOBI_BTC("huobi-btc", "hbtc", "Huobi BTC"),
    OKC("oec-token", "okt", "OKC"),
    IOTEX("iotex", "iotx", "IoTeX"),
    GOLEM("golem", "glm", "Golem"),
    YEARN_FINANCE("yearn-finance", "yfi", "yearn.finance"),
    JUST("just", "jst", "JUST"),
    ESCOIN("escoin-token", "elg", "Escoin"),
    MARINADE_STAKED_SOL("msol", "msol", "Marinade staked SOL"),
    LIVEPEER("livepeer", "lpt", "Livepeer"),
    CONVEX_CRV("convex-crv", "cvxcrv", "Convex CRV"),
    ANKR("ankr", "ankr", "Ankr"),
    SUSHI("sushi", "sushi", "Sushi"),
    POLYMATH("polymath", "poly", "Polymath"),
    OMG_NETWORK("omisego", "omg", "OMG Network"),
    HARMONY("harmony", "one", "Harmony"),
    CONSTELLATION("constellation-labs", "dag", "Constellation"),
    ZERO_X("0x", "zrx", "0x"),
    MAGIC_INTERNET_MONEY("magic-internet-money", "mim", "Magic Internet Money"),
    EURO_TETHER("tether-eurt", "eurt", "Euro Tether"),
    BITGERT("bitrise-token", "brise", "Bitgert"),
    ICON("icon", "icx", "ICON"),
    JUNO("juno-network", "juno", "JUNO"),
    TENSET("tenset", "10set", "Tenset"),
    ROCKET_POOL_ETH("rocket-pool-eth", "reth", "Rocket Pool ETH"),
    FLUX("zelcash", "flux", "Flux"),
    SYNAPSE("synapse-2", "syn", "Synapse"),
    MOONBEAM("moonbeam", "glmr", "Moonbeam"),
    HUSD("husd", "husd", "HUSD"),
    DYDX("dydx", "dydx", "dYdX"),
    BABY_DOGE_COIN("baby-doge-coin", "babydoge", "Baby Doge Coin"),
    WAX("wax", "waxp", "WAX"),
    LINK("link", "ln", "LINK"),
    ONTOLOGY("ontology", "ont", "Ontology"),
    SWISSBORG("swissborg", "chsb", "SwissBorg"),
    HIVE("hive", "hive", "Hive"),
    NUCYPHER("nucypher", "nu", "NuCypher"),
    MERIT_CIRCLE("merit-circle", "mc", "Merit Circle"),
    BALANCER("balancer", "bal", "Balancer"),
    ALCHEMIX_USD("alchemix-usd", "alusd", "Alchemix USD"),
    COINMETRO("coinmetro", "xcm", "Coinmetro"),
    LIQUITY_USD("liquity-usd", "lusd", "Liquity USD"),
    DECENTRALIZED_SOCIAL("bitclout", "deso", "Decentralized Social"),
    WOO_NETWORK("woo-network", "woo", "WOO Network"),
    SIACOIN("siacoin", "sc", "Siacoin"),
    SONGBIRD("songbird", "sgb", "Songbird"),
    CHIA("chia", "xch", "Chia"),
    ENERGY_WEB("energy-web-token", "ewt", "Energy Web"),
    HORIZEN("zencash", "zen", "Horizen"),
    UMA("uma", "uma", "UMA"),
    SECRET("secret", "scrt", "Secret"),
    OPTIMISM("optimism", "op", "Optimism"),
    SXP("swipe", "sxp", "SXP"),
    VVS_FINANCE("vvs-finance", "vvs", "VVS Finance"),
    APENFT("apenft", "nft", "APENFT"),
    AUDIUS("audius", "audio", "Audius"),
    SAFEMOON("safemoon-2", "sfm", "SafeMoon"),
    RIBBON_FINANCE("ribbon-finance", "rbn", "Ribbon Finance"),
    DAO_MAKER("dao-maker", "dao", "DAO Maker"),
    MXC("mxc", "mxc", "MXC"),
    PLAYDAPP("playdapp", "pla", "PlayDapp"),
    ERGO("ergo", "erg", "Ergo"),
    COINEX("coinex-token", "cet", "CoinEx"),
    SKALE("skale", "skl", "SKALE"),
    DIGIBYTE("digibyte", "dgb", "DigiByte"),
    RICH_QUACK("richquack", "quack", "Rich Quack"),
    INJECTIVE("injective-protocol", "inj", "Injective"),
    LISK("lisk", "lsk", "Lisk"),
    DOGELON_MARS("dogelon-mars", "elon", "Dogelon Mars"),
    STATUS("status", "snt", "Status"),
    SMOOTH_LOVE_POTION("smooth-love-potion", "slp", "Smooth Love Potion"),
    LIDO_STAKED_SOL("lido-staked-sol", "stsol", "Lido Staked SOL"),
    ASTAR("astar", "astr", "Astar"),
    NERVOS_NETWORK("nervos-network", "ckb", "Nervos Network"),
    FUNCTION_X("fx-coin", "fx", "Function X"),
    RENDER("render-token", "rndr", "Render"),
    KIROBO("kirobo", "kiro", "Kirobo"),
    STASIS_EURO("stasis-eurs", "eurs", "STASIS EURO"),
    NEUTRINO_USD("neutrino", "usdn", "Neutrino USD"),
    PUNDI_X("pundi-x-2", "pundix", "Pundi X"),
    VOYAGER_VGX("ethos", "vgx", "Voyager VGX"),
    BITKUB_COIN("bitkub-coin", "kub", "Bitkub Coin"),
    LOOKSRARE("looksrare", "looks", "LooksRare"),
    COTI("coti", "coti", "COTI"),
    REN("republic-protocol", "ren", "REN"),
    UQUID_COIN("uquid-coin", "uqc", "Uquid Coin"),
    PLATONCOIN("platoncoin", "pltc", "PlatonCoin"),
    REEF("reef", "reef", "Reef"),
    CEEK_SMART_VR("ceek", "ceek", "CEEK Smart VR"),
    DEJITARU_TSUKA("dejitaru-tsuka", "tsuka", "Dejitaru Tsuka"),
    VELAS("velas", "vlx", "Velas"),
    COIN_OF_THE_CHAMPIONS("coin-of-the-champions", "coc", "Coin of the champions"),
    METIS("metis-token", "metis", "Metis"),
    CONSTITUTIONDAO("constitutiondao", "people", "ConstitutionDAO"),
    API3("api3", "api3", "API3"),
    TEMPLEDAO("temple", "temple", "TempleDAO"),
    NANO("nano", "xno", "Nano"),
    SCHOLARSHIP_COIN("scholarship-coin", "scho", "Scholarship Coin"),
    USDX("usdx", "usdx", "USDX"),
    MAPLE("maple", "mpl", "Maple"),
    KYBER_NETWORK_CRYSTAL("kyber-network-crystal", "knc", "Kyber Network Crystal"),
    KUJIRA("kujira", "kuji", "Kujira"),
    WINKLINK("wink", "win", "WINkLink"),
    PROM("prometeus", "prom", "Prom"),
    MEDIBLOC("medibloc", "med", "Medibloc"),
    BTSE_TOKEN("btse-token", "btse", "BTSE Token"),
    TRIBE("tribe-2", "tribe", "Tribe"),
    ORBS("orbs", "orbs", "Orbs"),
    BOBA_NETWORK("boba-network", "boba", "Boba Network"),
    CIVIC("civic", "cvc", "Civic"),
    PLEX("plex", "plex", "PLEX"),
    POOLLOTTO_FINANCE("poollotto-finance", "plt", "Poollotto.finance"),
    ARDOR("ardor", "ardr", "Ardor"),
    SINGULARITYNET("singularitynet", "agix", "SingularityNET"),
    MVL("mass-vehicle-ledger", "mvl", "MVL"),
    SPELL("spell-token", "spell", "Spell"),
    SYSCOIN("syscoin", "sys", "Syscoin"),
    MOBOX("mobox", "mbox", "Mobox"),
    NEST_PROTOCOL("nest", "nest", "Nest Protocol"),
    E_RADIX("e-radix", "exrd", "e-Radix"),
    STEEM("steem", "steem", "Steem"),
    MX("mx-token", "mx", "MX"),
    VERITASEUM("veritaseum", "veri", "Veritaseum"),
    NUMERAIRE("numeraire", "nmr", "Numeraire"),
    POCKET_NETWORK("pocket-network", "pokt", "Pocket Network"),
    RADIO_CACA("radio-caca", "raca", "Radio Caca"),
    MY_NEIGHBOR_ALICE("my-neighbor-alice", "alice", "My Neighbor Alice"),
    WAZIRX("wazirx", "wrx", "WazirX"),
    HXRO("hxro", "hxro", "Hxro"),
    ACALA("acala", "aca", "Acala"),
    MDEX("mdex", "mdx", "Mdex"),
    ASCENDEX("asd", "asd", "AscendEx"),
    GALXE("project-galaxy", "gal", "Galxe"),
    DENT("dent", "dent", "Dent"),
    COIN98("coin98", "c98", "Coin98"),
    SETH2("seth2", "seth2", "sETH2"),
    RADICLE("radicle", "rad", "Radicle"),
    ULTRA("ultra", "uos", "Ultra"),
    PERSISTENCE("persistence", "xprt", "Persistence"),
    BENQI_LIQUID_STAKED_AVAX("benqi-liquid-staked-avax", "savax", "BENQI Liquid Staked AVAX"),
    GAINS_FARM("gains-farm", "gfarm2", "Gains Farm"),
    TELCOIN("telcoin", "tel", "Telcoin"),
    DECIMAL("decimal", "del", "Decimal"),
    WRAPPED_CENTRIFUGE("wrapped-centrifuge", "wcfg", "Wrapped Centrifuge"),
    CHROMIA("chromaway", "chr", "Chromia"),
    CARTESI("cartesi", "ctsi", "Cartesi"),
    CENTRIFUGE("centrifuge", "cfg", "Centrifuge"),
    BANCOR_NETWORK("bancor", "bnt", "Bancor Network"),
    DKARGO("dkargo", "dka", "dKargo"),
    CELER_NETWORK("celer-network", "celr", "Celer Network"),
    XSUSHI("xsushi", "xsushi", "xSUSHI"),
    NERVE_FINANCE("nerve-finance", "nrv", "Nerve Finance"),
    MAGIC("magic", "magic", "Magic"),
    POWER_LEDGER("power-ledger", "powr", "Power Ledger"),
    BISWAP("biswap", "bsw", "Biswap"),
    FUN("funfair", "fun", "FUN"),
    IEXEC_RLC("iexec-rlc", "rlc", "iExec RLC"),
    MAIDSAFECOIN("maidsafecoin", "emaid", "MaidSafeCoin"),
    BICONOMY("biconomy", "bico", "Biconomy"),
    CONFLUX("conflux-token", "cfx", "Conflux"),
    SHENTU("certik", "ctk", "Shentu"),
    XYO_NETWORK("xyo-network", "xyo", "XYO Network"),
    EURO_COIN("euro-coin", "euroc", "Euro Coin"),
    AURORA("aurora-near", "aurora", "Aurora"),
    KEEP_NETWORK("keep-network", "keep", "Keep Network"),
    REQUEST("request-network", "req", "Request"),
    STRATIS("stratis", "strax", "Stratis"),
    PIRATE_CHAIN("pirate-chain", "arrr", "Pirate Chain"),
    BELDEX("beldex", "bdx", "Beldex"),
    CREDITCOIN("creditcoin-2", "ctc", "Creditcoin"),
    QUARKCHAIN("quark-chain", "qkc", "QuarkChain"),
    VETHOR("vethor-token", "vtho", "VeThor"),
    MIL_K_ALLIANCE("milk-alliance", "mlk", "MiL.k Alliance"),
    SSV_NETWORK("ssv-network", "ssv", "SSV Network"),
    FLEXUSD("flex-usd", "flexusd", "flexUSD"),
    ILLUVIUM("illuvium", "ilv", "Illuvium"),
    DOCK("dock", "dock", "Dock"),
    SEEDIFY_FUND("seedify-fund", "sfund", "Seedify.fund"),
    RAYDIUM("raydium", "ray", "Raydium"),
    EVERSCALE("everscale", "ever", "Everscale"),
    LUKSO("lukso-token", "lyxe", "LUKSO"),
    ANKR_REWARD_BEARING_STAKED_ETH("ankreth", "aethc", "Ankr Reward-Bearing Staked ETH"),
    SHARE("sharering", "shr", "Share"),
    ORIGIN_PROTOCOL("origin-protocol", "ogn", "Origin Protocol"),
    STP("stp-network", "stpt", "STP"),
    FLOKI_INU("floki-inu", "floki", "Floki Inu"),
    CHAINX("chainx", "pcx", "ChainX"),
    FIDU("fidu", "fidu", "Fidu"),
    EULER("euler", "eul", "Euler"),
    KILT_PROTOCOL("kilt-protocol", "kilt", "KILT Protocol"),
    SX_NETWORK("sx-network", "sx", "SX Network"),
    TOKAMAK_NETWORK("tokamak-network", "ton", "Tokamak Network"),
    H2O_DAO("h2o-dao", "h2o", "H2O Dao"),
    VENUS("venus", "xvs", "Venus"),
    ORIGINTRAIL("origintrail", "trac", "OriginTrail"),
    JOE("joe", "joe", "JOE"),
    SUSD("nusd", "susd", "sUSD"),
    NEBLIO("neblio", "nebl", "Neblio"),
    OCEAN_PROTOCOL("ocean-protocol", "ocean", "Ocean Protocol"),
    MULTICHAIN("multichain", "multi", "Multichain"),
    BIFROST("bifrost", "bfc", "Bifrost"),
    GAINS_NETWORK("gains-network", "gns", "Gains Network"),
    METAL("metal", "mtl", "Metal"),
    BLOX("blox", "cdt", "Blox"),
    CONCORDIUM("concordium", "ccd", "Concordium"),
    INSURE_DEFI("insure", "sure", "inSure DeFi"),
    ALIEN_WORLDS("alien-worlds", "tlm", "Alien Worlds"),
    CUBE("cube", "itamcube", "CUBE"),
    EFFORCE("wozx", "wozx", "Efforce"),
    STORMX("storm", "stmx", "StormX"),
    BTC_STANDARD_HASHRATE_TOKEN("btc-standard-hashrate-token", "btcst", "BTC Standard Hashrate Token"),
    REVAIN("revain", "rev", "Revain"),
    ARAGON("aragon", "ant", "Aragon"),
    BONE_SHIBASWAP("bone-shibaswap", "bone", "Bone ShibaSwap"),
    ARK("ark", "ark", "Ark"),
    RALLY("rally-2", "rly", "Rally"),
    HERMEZ_NETWORK("hermez-network-token", "hez", "Hermez Network"),
    LIQUITY("liquity", "lqty", "Liquity"),
    RENBTC("renbtc", "renbtc", "renBTC"),
    YIELD_GUILD_GAMES("yield-guild-games", "ygg", "Yield Guild Games"),
    STARGATE_FINANCE("stargate-finance", "stg", "Stargate Finance"),
    STORJ("storj", "storj", "Storj"),
    CVAULT_FINANCE("cvault-finance", "core", "cVault.finance"),
    AELF("aelf", "elf", "aelf"),
    SANTOS_FC_FAN_TOKEN("santos-fc-fan-token", "santos", "Santos FC Fan Token"),
    SWEATCOIN_SWEAT_ECONOMY("sweatcoin", "sweat", "Sweatcoin - Sweat Economy"),
    RAI_FINANCE("rai-finance", "sofi", "RAI Finance"),
    FEI_USD("fei-usd", "fei", "Fei USD"),
    METER_GOVERNANCE("meter", "mtrg", "Meter Governance"),
    XIDO_FINANCE("xido-finance", "xido", "Xido Finance"),
    UTRUST("utrust", "utk", "Utrust"),
    MANIFOLD_FINANCE("manifold-finance", "fold", "Manifold Finance"),
    MOONRIVER("moonriver", "movr", "Moonriver"),
    ADSHARES("adshares", "ads", "Adshares"),
    BETA_FINANCE("beta-finance", "beta", "Beta Finance"),
    EVERIPEDIA("everipedia", "iq", "Everipedia"),
    BILIRA("bilira", "tryb", "BiLira"),
    AERGO("aergo", "aergo", "Aergo"),
    BORINGDAO_OLD("boringdao-[old]", "bor", "BoringDAO [OLD]"),
    ORCHID_PROTOCOL("orchid-protocol", "oxt", "Orchid Protocol"),
    SAITAMA("saitama-inu", "saitama", "Saitama"),
    NKN("nkn", "nkn", "NKN"),
    FETCH_AI("fetch-ai", "fet", "Fetch.ai"),
    DAWN_PROTOCOL("dawn-protocol", "dawn", "Dawn Protocol"),
    AUGUR("augur", "rep", "Augur"),
    DIVI("divi", "divi", "Divi"),
    GUILD_OF_GUARDIANS("guild-of-guardians", "gog", "Guild of Guardians"),
    BADGER_DAO("badger-dao", "badger", "Badger DAO"),
    HOLORIDE("holoride", "ride", "holoride"),
    EFINITY("efinity", "efi", "Efinity"),
    UFO_GAMING("ufo-gaming", "ufo", "UFO Gaming"),
    XMON("xmon", "xmon", "XMON"),
    STRIKE("strike", "strk", "Strike"),
    CELO_DOLLAR("celo-dollar", "cusd", "Celo Dollar"),
    ALCHEMY_PAY("alchemy-pay", "ach", "Alchemy Pay"),
    MAI("mimatic", "mimatic", "MAI"),
    DERO("dero", "dero", "Dero"),
    AAVEGOTCHI("aavegotchi", "ghst", "Aavegotchi"),
    XSGD("xsgd", "xsgd", "XSGD"),
    VERGE("verge", "xvg", "Verge"),
    PHOENIX_GLOBAL_OLD("red-pulse", "phb", "Phoenix Global [OLD]"),
    KODA_CRYPTOCURRENCY("koda-finance", "koda", "Koda Cryptocurrency"),
    METADIUM("metadium", "meta", "Metadium"),
    MASK_NETWORK("mask-network", "mask", "Mask Network"),
    BITCICOIN("bitcicoin", "bitci", "Bitcicoin"),
    NEXUS("nexus", "nxs", "Nexus"),
    RSK_INFRASTRUCTURE_FRAMEWORK("rif-token", "rif", "RSK Infrastructure Framework"),
    ELECTRONEUM("electroneum", "etn", "Electroneum"),
    DUSK_NETWORK("dusk-network", "dusk", "DUSK Network"),
    ALPHA_VENTURE_DAO("alpha-finance", "alpha", "Alpha Venture DAO"),
    SUN_TOKEN("sun-token", "sun", "Sun Token"),
    AKASH_NETWORK("akash-network", "akt", "Akash Network"),
    DODO("dodo", "dodo", "DODO"),
    GODS_UNCHAINED("gods-unchained", "gods", "Gods Unchained"),
    WRAPPED_NXM("wrapped-nxm", "wnxm", "Wrapped NXM"),
    ETHERNITY_CHAIN("ethernity-chain", "ern", "Ethernity Chain"),
    FREEWAY("freeway", "fwt", "Freeway"),
    TAMADOGE("tamadoge", "tama", "Tamadoge"),
    TELOS("telos", "tlos", "Telos"),
    DOPEX("dopex", "dpx", "Dopex"),
    WORLD_MOBILE_TOKEN("world-mobile-token", "wmt", "World Mobile Token"),
    BARNBRIDGE("barnbridge", "bond", "BarnBridge"),
    FERRO("ferro", "fer", "Ferro"),
    IRON_BANK_EURO("iron-bank-euro", "ibeur", "Iron Bank EURO"),
    BOLIDE("bolide", "blid", "Bolide"),
    MANCIUM("mancium", "manc", "Mancium"),
    XCAD_NETWORK("xcad-network", "xcad", "XCAD Network"),
    ZIGZAG("zigzag-2", "zz", "ZigZag"),
    BIT2ME("bit2me", "b2m", "Bit2Me"),
    SHARDUS("shardus", "ult", "Shardus"),
    BAND_PROTOCOL("band-protocol", "band", "Band Protocol"),
    TITANSWAP("titanswap", "titan", "TitanSwap"),
    STARGAZE("stargaze", "stars", "Stargaze"),
    HIFI_FINANCE("mainframe", "mft", "Hifi Finance"),
    AMPLEFORTH("ampleforth", "ampl", "Ampleforth"),
    EVERGROW_COIN("evergrowcoin", "egc", "EverGrow Coin"),
    AXION("axion", "axn", "Axion"),
    DOLA("dola-usd", "dola", "Dola"),
    THUNDERCORE("thunder-token", "tt", "ThunderCore"),
    MRWEB_FINANCE_OLD("mrweb-finance", "ama", "MrWeb Finance [OLD]"),
    ALPACA_FINANCE("alpaca-finance", "alpaca", "Alpaca Finance"),
    USDK("usdk", "usdk", "USDK"),
    POLKASTARTER("polkastarter", "pols", "Polkastarter"),
    EVERDOME("everdome", "dome", "Everdome"),
    CBAT("compound-basic-attention-token", "cbat", "cBAT"),
    BAKERYSWAP("bakerytoken", "bake", "BakerySwap"),
    ZIGNALY("zignaly", "zig", "Zignaly"),
    BOUNCE("auction", "auction", "Bounce"),
    AGEUR("ageur", "ageur", "agEUR"),
    KI("ki", "xki", "KI"),
    KOINOS("koinos", "koin", "Koinos"),
    CHRONO_TECH("chronobank", "time", "chrono.tech"),
    TRACER_DAO("tracer-dao", "tcr", "Tracer DAO"),
    FLAMINGO_FINANCE("flamingo-finance", "flm", "Flamingo Finance"),
    ORIGIN_DOLLAR("origin-dollar", "ousd", "Origin Dollar"),
    COINWEB("coinweb", "cweb", "Coinweb"),
    CANTO("canto", "canto", "CANTO"),
    AUTOMATA("automata", "ata", "Automata"),
    QREDO("qredo", "qrdo", "Qredo"),
    KEEP3RV1("keep3rv1", "kp3r", "Keep3rV1"),
    LCX("lcx", "lcx", "LCX"),
    DEI("dei-token", "dei", "DEI"),
    LOOM_NETWORK_OLD("loom-network", "loomold", "Loom Network (OLD)"),
    KUNCI_COIN("kunci-coin", "kunci", "Kunci Coin"),
    AVINOC("avinoc", "avinoc", "AVINOC"),
    TRUEFI("truefi", "tru", "TrueFi"),
    VERASITY("verasity", "vra", "Verasity"),
    DFI_MONEY("yfii-finance", "yfii", "DFI.money"),
    VEGA_PROTOCOL("vega-protocol", "vega", "Vega Protocol"),
    SAFEPAL("safepal", "sfp", "SafePal"),
    COCOS_BCX("cocos-bcx", "cocos", "COCOS BCX"),
    RARESAMA("raresama", "poop", "Raresama"),
    HUNT("hunt-token", "hunt", "Hunt"),
    RONIN("ronin", "ron", "Ronin"),
    HYPERCASH("hshare", "hc", "HyperCash"),
    KISHU_INU("kishu-inu", "kishu", "Kishu Inu"),
    GXCHAIN("gxchain", "gxc", "GXChain"),
    IDEX("aurora-dao", "idex", "IDEX"),
    ASTRAFER("astrafer", "astrafer", "Astrafer"),
    KRYPTON_DAO("krypton-dao", "krd", "Krypton DAO"),
    KLEVER("klever", "klv", "Klever"),
    PERPETUAL_PROTOCOL("perpetual-protocol", "perp", "Perpetual Protocol"),
    MARLIN("marlin", "pond", "Marlin"),
    TOMOCHAIN("tomochain", "tomo", "TomoChain"),
    TRAVALA_COM("concierge-io", "ava", "Travala.com"),
    COVALENT("covalent", "cqt", "Covalent"),
    VOLT_INU("volt-inu-2", "volt", "Volt Inu"),
    UNIFI_PROTOCOL_DAO("unifi-protocol-dao", "unfi", "Unifi Protocol DAO"),
    HYDRA("hydra", "hydra", "Hydra"),
    ORION_PROTOCOL("orion-protocol", "orn", "Orion Protocol"),
    AMPLEFORTH_GOVERNANCE("ampleforth-governance-token", "forth", "Ampleforth Governance"),
    ITHEUM("itheum", "itheum", "Itheum"),
    SNOWBANK("snowbank", "sb", "Snowbank"),
    SUPERFARM("superfarm", "super", "SuperFarm"),
    ROOTKIT("rootkit", "root", "Rootkit"),
    TELLOR("tellor", "trb", "Tellor"),
    CARRY("carry", "cre", "Carry"),
    CLOVER_FINANCE("clover-finance", "clv", "Clover Finance"),
    ALPINE_F1_TEAM_FAN_TOKEN("alpine-f1-team-fan-token", "alpine", "Alpine F1 Team Fan Token"),
    WANCHAIN("wanchain", "wan", "Wanchain"),
    REFINABLE("refinable", "fine", "Refinable"),
    UMEE("umee", "umee", "Umee"),
    LEAGUE_OF_KINGDOMS("league-of-kingdoms", "loka", "League of Kingdoms"),
    IX("ix-token", "ixt", "IX"),
    CLEARPOOL("clearpool", "cpool", "Clearpool"),
    DIA("dia-data", "dia", "DIA"),
    AIOZ_NETWORK("aioz-network", "aioz", "AIOZ Network"),
    ELLIPSIS_OLD("ellipsis", "eps", "Ellipsis [OLD]"),
    MRWEB_FINANCE("mrweb-finance-2", "ama", "MrWeb Finance"),
    DOGE_KILLER("leash", "leash", "Doge Killer"),
    BEAN("bean", "bean", "Bean"),
    ZOIDPAY("zoid-pay", "zpay", "ZoidPay"),
    OPTIMUS_OPT2("optimus-opt2", "opt2", "Optimus OPT2"),
    YUSD_STABLECOIN("yusd-stablecoin", "yusd", "YUSD Stablecoin"),
    PYLON_PROTOCOL("pylon-protocol", "mine", "Pylon Protocol"),
    PHALA_NETWORK("pha", "pha", "Phala Network"),
    AETERNITY("aeternity", "ae", "Aeternity"),
    BOX_TOKEN("box-token", "box", "BOX Token"),
    MIRROR_PROTOCOL("mirror-protocol", "mir", "Mirror Protocol"),
    CARGOX("cargox", "cxo", "CargoX"),
    CELO_EURO("celo-euro", "ceur", "Celo Euro"),
    SPLINTERSHARDS("splinterlands", "sps", "Splintershards"),
    REGEN("regen", "regen", "Regen"),
    ARPA_CHAIN("arpa-chain", "arpa", "ARPA Chain"),
    ANCHOR_PROTOCOL("anchor-protocol", "anc", "Anchor Protocol"),
    PROPY("propy", "pro", "Propy"),
    ELASTOS("elastos", "ela", "Elastos"),
    KOMODO("komodo", "kmd", "Komodo"),
    DESTABLECOIN_HAY("helio-protocol-hay", "hay", "Destablecoin HAY"),
    METAHERO("metahero", "hero", "Metahero"),
    KARDIACHAIN("kardiachain", "kai", "KardiaChain"),
    SWARM("swarm-bzz", "bzz", "Swarm"),
    ALCHEMIX("alchemix", "alcx", "Alchemix"),
    TOUCAN_PROTOCOL_BASE_CARBON_TONNE("toucan-protocol-base-carbon-tonne", "bct", "Toucan Protocol: Base Carbon Tonne"),
    BELLA_PROTOCOL("bella-protocol", "bel", "Bella Protocol"),
    BITCOIN_DIAMOND("bitcoin-diamond", "bcd", "Bitcoin Diamond"),
    GENSOKISHI_METAVERSE("gensokishis-metaverse", "mv", "GensoKishi Metaverse"),
    LAZIO_FAN_TOKEN("lazio-fan-token", "lazio", "Lazio Fan Token"),
    LINEAR("linear", "lina", "Linear"),
    SERO("super-zero", "sero", "SERO"),
    REDACTED("redacted", "btrfly", "Redacted"),
    GAS("gas", "gas", "Gas"),
    MOSSLAND("mossland", "moc", "Mossland"),
    DEFI_PULSE_INDEX("defipulse-index", "dpi", "DeFi Pulse Index"),
    KASPA("kaspa", "kas", "Kaspa"),
    INSTADAPP_ETH("instadapp-eth", "ieth", "Instadapp ETH"),
    UNIDEF("unidef", "u", "Unidef"),
    CUBE_NETWORK("cube-network", "cube", "Cube Network"),
    INSTAR("insights-network", "instar", "INSTAR"),
    REFEREUM("refereum", "rfr", "Refereum"),
    CUNI("compound-uniswap", "cuni", "cUNI"),
    RESERVE("reserve", "rsv", "Reserve"),
    MINTED("minted", "mtd", "Minted"),
    ALPHA_QUARK("alpha-quark-token", "aqt", "Alpha Quark"),
    PROTON("proton", "xpr", "Proton"),
    SAITO("saito", "saito", "Saito"),
    REI_NETWORK("rei-network", "rei", "REI Network"),
    SMARTOFGIVING("smartofgiving", "aog", "smARTOFGIVING"),
    VITE("vite", "vite", "Vite"),
    DEAPCOIN("deapcoin", "dep", "DEAPCOIN"),
    MANGO("mango-markets", "mngo", "Mango"),
    ICHI("ichi-farm", "ichi", "ICHI"),
    BITMART("bitmart-token", "bmx", "BitMart"),
    BRAZIL_NATIONAL_FOOTBALL_TEAM_FAN_TOKEN("brazil-fan-token", "bft", "Brazil National Football Team Fan Token"),
    BNB48_CLUB("bnb48-club-token", "koge", "BNB48 Club"),
    UNIZEN("unizen", "zcx", "Unizen"),
    ENZYME("melon", "mln", "Enzyme"),
    CLOUTCONTRACTS("cloutcontracts", "ccs", "CloutContracts"),
    ION("ion", "ion", "Ion"),
    FIRMACHAIN("firmachain", "fct", "Firmachain"),
    BITSHARES("bitshares", "bts", "BitShares"),
    LTO_NETWORK("lto-network", "lto", "LTO Network"),
    MSTABLE_USD("musd", "musd", "mStable USD"),
    STEEM_DOLLARS("steem-dollars", "sbd", "Steem Dollars"),
    CERE_NETWORK("cere-network", "cere", "Cere Network"),
    QUICKSWAP_OLD("quick", "quick", "Quickswap [OLD]"),
    LYRA_FINANCE("lyra-finance", "lyra", "Lyra Finance"),
    RARI_GOVERNANCE("rari-governance-token", "rgt", "Rari Governance"),
    CULT_DAO("cult-dao", "cult", "Cult DAO"),
    FORTA("forta", "fort", "Forta"),
    BLUZELLE("bluzelle", "blz", "Bluzelle"),
    BEZOGE_EARTH("bezoge-earth", "bezoge", "Bezoge Earth"),
    ONBUFF("onbuff", "onit", "ONBUFF"),
    YIELDIFICATION("yieldification", "ydf", "Yieldification"),
    STEP_APP("step-app-fitfi", "fitfi", "Step App"),
    KAVA_LEND("kava-lend", "hard", "Kava Lend"),
    DECENTRAL_GAMES("decentral-games", "dg", "Decentral Games"),
    SYNTROPY("noia-network", "noia", "Syntropy"),
    FIRO("zcoin", "firo", "Firo"),
    STARLINK("starlink", "starl", "StarLink"),
    FIO_PROTOCOL("fio-protocol", "fio", "FIO Protocol"),
    LITENTRY("litentry", "lit", "Litentry"),
    MINTME_COM_COIN("webchain", "mintme", "MintMe.com Coin"),
    MORPHEUS_NETWORK("morpheus-network", "mnw", "Morpheus Network"),
    GLOBIANCE_EXCHANGE("globiance-exchange", "gbex", "Globiance Exchange"),
    KYBER_NETWORK_CRYSTAL_LEGACY("kyber-network", "kncl", "Kyber Network Crystal Legacy"),
    AAVE_OLD("ethlend", "lend", "Aave [OLD]"),
    CHOISE_COM("choise", "cho", "Choise.com"),
    JASMYCOIN("jasmycoin", "jasmy", "JasmyCoin"),
    YOSHI_EXCHANGE("yoshi-exchange", "yoshi", "Yoshi.exchange"),
    CALLISTO_NETWORK("callisto", "clo", "Callisto Network"),
    RIZON("rizon", "atolo", "RIZON"),
    BEEFY_FINANCE("beefy-finance", "bifi", "Beefy.Finance"),
    PHANTASMA("phantasma", "soul", "Phantasma"),
    PARIS_SAINT_GERMAIN_FAN_TOKEN("paris-saint-germain-fan-token", "psg", "Paris Saint-Germain Fan Token"),
    RARIBLE("rarible", "rari", "Rarible"),
    BZX_PROTOCOL("bzx-protocol", "bzrx", "bZx Protocol"),
    GET_PROTOCOL("get-token", "get", "GET Protocol"),
    ALLIANCEBLOCK("allianceblock", "albt", "AllianceBlock"),
    SELFKEY("selfkey", "key", "SelfKey"),
    DISTRICT0X("district0x", "dnt", "district0x"),
    GYEN("gyen", "gyen", "GYEN"),
    ADVENTURE_GOLD("adventure-gold", "agld", "Adventure Gold"),
    BENQI("benqi", "qi", "BENQI"),
    PLUTON("pluton", "plu", "Pluton"),
    GROESTLCOIN("groestlcoin", "grs", "Groestlcoin"),
    KLIMA_DAO("klima-dao", "klima", "Klima DAO"),
    NEUTRINO_SYSTEM_BASE("neutrino-system-base-token", "nsbt", "Neutrino System Base"),
    CRESCENT_NETWORK("crescent-network", "cre", "Crescent Network"),
    HECTOR_NETWORK("hector-dao", "hec", "Hector Network"),
    MANCHESTER_CITY_FAN_TOKEN("manchester-city-fan-token", "city", "Manchester City Fan Token"),
    MAP_PROTOCOL("marcopolo", "map", "MAP Protocol"),
    SINGULARITYDAO("singularitydao", "sdao", "SingularityDAO"),
    RAMP_OLD("ramp", "ramp", "RAMP [OLD]"),
    PRESEARCH("presearch", "pre", "Presearch"),
    GITCOIN("gitcoin", "gtc", "Gitcoin"),
    KIN("kin", "kin", "Kin"),
    IRISNET("iris-network", "iris", "IRISnet"),
    WING_FINANCE("wing-finance", "wing", "Wing Finance"),
    HARVEST_FINANCE("harvest-finance", "farm", "Harvest Finance"),
    UNIBRIGHT("unibright", "ubt", "Unibright"),
    TOKENPOCKET_TOKEN("token-pocket", "tpt", "TokenPocket Token"),
    SPHERE_FINANCE("sphere-finance", "sphere", "Sphere Finance"),
    AIRSWAP("airswap", "ast", "AirSwap"),
    HOO("hoo-token", "hoo", "Hoo"),
    SHIBA_PREDATOR("shiba-predator", "qom", "Shiba Predator"),
    PHOENIX_GLOBAL("phoenix-global", "phb", "Phoenix Global"),
    TALKEN("talken", "talk", "Talken"),
    VICTORIA_VR("victoria-vr", "vr", "Victoria VR"),
    DEFIGRAM("defigram", "dfg", "Defigram"),
    SAMOYEDCOIN("samoyedcoin", "samo", "Samoyedcoin"),
    EVERRISE("everrise", "rise", "EverRise"),
    BONFIDA("bonfida", "fida", "Bonfida"),
    STREAMR("streamr", "data", "Streamr"),
    DOPEX_REBATE("dopex-rebate-token", "rdpx", "Dopex Rebate"),
    CRATOS("cratos", "crts", "Cratos"),
    ROOK("rook", "rook", "Rook"),
    VERUS_COIN("verus-coin", "vrsc", "Verus Coin"),
    AMBIRE_ADEX("adex", "adx", "Ambire AdEx"),
    SOMNIUM_SPACE_CUBES("somnium-space-cubes", "cube", "Somnium Space CUBEs"),
    PLATON_NETWORK("platon-network", "lat", "PlatON Network"),
    SPORTIUM("sportium", "sprt", "Sportium"),
    SUPERRARE("superrare", "rare", "SuperRare"),
    GLOBAL_COIN_RESEARCH("global-coin-research", "gcr", "Global Coin Research"),
    AURA_FINANCE("aura-finance", "aura", "Aura Finance"),
    LEVERFI("lever", "lever", "LeverFi"),
    ALEPH_IM("aleph", "aleph", "Aleph.im"),
    RAILGUN("railgun", "rail", "Railgun"),
    CATECOIN("catecoin", "cate", "CateCoin"),
    RMRK("rmrk", "rmrk", "RMRK"),
    FUSE("fuse-network-token", "fuse", "Fuse"),
    PSTAKE_FINANCE("pstake-finance", "pstake", "pSTAKE Finance"),
    BITRUE_COIN("bitrue-token", "btr", "Bitrue Coin"),
    CIRCUITS_OF_VALUE("circuits-of-value", "coval", "Circuits of Value"),
    FINDORA("findora", "fra", "Findora"),
    ROUTER_PROTOCOL("route", "route", "Router Protocol"),
    PIVX("pivx", "pivx", "PIVX"),
    SAI("sai", "sai", "Sai"),
    WILDER_WORLD("wilder-world", "wild", "Wilder World"),
    BEAM("beam", "beam", "BEAM"),
    FC_BARCELONA_FAN_TOKEN("fc-barcelona-fan-token", "bar", "FC Barcelona Fan Token"),
    BOSON_PROTOCOL("boson-protocol", "boson", "Boson Protocol"),
    CUDOS("cudos", "cudos", "Cudos"),
    MANTRA("mantra-dao", "om", "MANTRA"),
    VAI("vai", "vai", "Vai"),
    STREAMR_XDATA("streamr-xdata", "xdata", "Streamr XDATA"),
    GENESYSGO_SHADOW("genesysgo-shadow", "shdw", "GenesysGo Shadow"),
    CORTEX("cortex", "ctxc", "Cortex"),
    SPERAX("sperax", "spa", "Sperax"),
    PINKSALE("pinksale", "pinksale", "PinkSale"),
    SENTINEL_PROTOCOL("sentinel-protocol", "upp", "Sentinel Protocol"),
    TRANCHESS("tranchess", "chess", "Tranchess"),
    FRONTIER("frontier-token", "front", "Frontier"),
    AXEL("axel", "axel", "AXEL"),
    QASH("qash", "qash", "QASH"),
    ORCA("orca", "orca", "Orca"),
    NYM("nym", "nym", "Nym"),
    GOLDFINCH("goldfinch", "gfi", "Goldfinch"),
    MIXMARVEL("mixmarvel", "mix", "MixMarvel"),
    ARGENTINE_FOOTBALL_ASSOCIATION_FAN_TOKEN("argentine-football-association-fan-token", "arg", "Argentine Football Association Fan Token"),
    CONTENTOS("contentos", "cos", "Contentos"),
    GOLDEN_SOCIETY_TOKEN_V2("golden-society-token-v2", "gdsy", "Golden Society Token V2"),
    KARURA("karura", "kar", "Karura"),
    HATHOR("hathor", "htr", "Hathor"),
    HANDSHAKE("handshake", "hns", "Handshake"),
    SETH("seth", "seth", "sETH"),
    NULS("nuls", "nuls", "Nuls"),
    ULTILEDGER("ultiledger", "ult", "Ultiledger"),
    ATPAY("atpay", "atpay", "AtPay"),
    DOGECHAIN("dogechain", "dc", "Dogechain"),
    UNILEND_FINANCE("unlend-finance", "uft", "UniLend Finance"),
    ALETHEA_ARTIFICIAL_LIQUID_INTELLIGENCE("alethea-artificial-liquid-intelligence-token", "ali", "Alethea Artificial Liquid Intelligence"),
    STAKE_DAO("stake-dao", "sdt", "Stake DAO"),
    DEFI_KINGDOMS("defi-kingdoms", "jewel", "DeFi Kingdoms"),
    STAFI("stafi", "fis", "Stafi"),
    SHIDEN_NETWORK("shiden", "sdn", "Shiden Network"),
    LATTICE("lattice-token", "ltx", "Lattice"),
    SOLEND("solend", "slnd", "Solend"),
    OVR("ovr", "ovr", "Ovr"),
    TOKOCRYPTO("tokocrypto", "tko", "Tokocrypto"),
    TOR("tor", "tor", "TOR"),
    AION("aion", "aion", "Aion"),
    DXDAO("dxdao", "dxd", "DXdao"),
    BATTLE_WORLD("battle-world", "bwo", "Battle World"),
    TRUSTSWAP("trustswap", "swap", "Trustswap"),
    RETREEB("treeb", "treeb", "Retreeb"),
    AIRDAO("amber", "amb", "AirDAO"),
    YIELD_APP("yield-app", "yld", "Yield App"),
    AUTO("auto", "auto", "Auto"),
    DEXE("dexe", "dexe", "DeXe"),
    C0X("compound-0x", "czrx", "c0x"),
    CLASH_OF_LILLIPUT("clash-of-lilliput", "col", "Clash of Lilliput"),
    SHAPESHIFT_FOX("shapeshift-fox-token", "fox", "ShapeShift FOX"),
    QMALL("qmall", "qmall", "Qmall"),
    MUX_PROTOCOL("mcdex", "mcb", "MUX Protocol"),
    CYPHERIUM("cypherium", "cph", "Cypherium"),
    PARSIQ("parsiq", "prq", "PARSIQ"),
    ADVERTISE_COIN("advertise-coin", "adco", "Advertise Coin"),
    FRAX_PRICE_INDEX_SHARE("frax-price-index-share", "fpis", "Frax Price Index Share"),
    WOONKLY_POWER("woonkly-power", "woop", "Woonkly Power"),
    POLYSWARM("polyswarm", "nct", "PolySwarm"),
    SOLVE("solve-care", "solve", "SOLVE"),
    TOKEMAK("tokemak", "toke", "Tokemak"),
    CAP("cap", "cap", "Cap"),
    BIGSHORTBETS("bigshortbets", "bigsb", "BigShortBets"),
    VITADAO("vitadao", "vita", "VitaDAO"),
    MEASURABLE_DATA("measurable-data-token", "mdt", "Measurable Data"),
    HI_DOLLAR("hi-dollar", "hi", "hi Dollar"),
    VECRV_DAO_YVAULT("vecrv-dao-yvault", "yve-crvdao", "veCRV-DAO yVault"),
    LBRY_CREDITS("lbry-credits", "lbc", "LBRY Credits"),
    FUSION("fsn", "fsn", "FUSION"),
    TOKENLON("tokenlon", "lon", "Tokenlon"),
    KLEROS("kleros", "pnk", "Kleros"),
    OOKI("ooki", "ooki", "Ooki"),
    MATH("math", "math", "MATH"),
    UXD_STABLECOIN("uxd-stablecoin", "uxd", "UXD Stablecoin"),
    BYTOM("bytom", "btm", "Bytom"),
    JADE_PROTOCOL("jade-protocol", "jade", "Jade Protocol"),
    BUX("blockport", "bux", "BUX"),
    AVENTUS("aventus", "avt", "Aventus"),
    GUILDFI("guildfi", "gf", "GuildFi"),
    FEG_BSC("feg-token-bsc", "feg", "FEG BSC"),
    STAKEWISE("stakewise", "swise", "StakeWise"),
    FLEX_COIN("flex-coin", "flex", "FLEX Coin"),
    DECENTRAL_GAMES_GOVERNANCE("decentral-games-governance", "xdg", "Decentral Games Governance"),
    VECTORSPACE_AI("vectorspace", "vxv", "Vectorspace AI"),
    THALES("thales", "thales", "Thales"),
    DELTA_EXCHANGE("delta-exchange-token", "deto", "Delta Exchange"),
    SNOWBLOSSOM("snowblossom", "snow", "SnowBlossom"),
    WAYKICHAIN("waykichain", "wicc", "WaykiChain"),
    AFFYN("affyn", "fyn", "Affyn"),
    TE_FOOD("te-food", "tone", "TE-FOOD"),
    RFOX("redfox-labs-2", "rfox", "RFOX"),
    THE_VIRTUA_KOLECT("the-virtua-kolect", "tvk", "The Virtua Kolect"),
    DERIVADAO("derivadao", "ddx", "DerivaDAO"),
    PROSPER("prosper", "pros", "Prosper"),
    NEWSCRYPTO_COIN("newscrypto-coin", "nwc", "Newscrypto Coin"),
    STEPN_GREEN_SATOSHI_TOKEN_ON_SOLANA("green-satoshi-token", "gst-sol", "STEPN Green Satoshi Token on Solana"),
    KRYLL("kryll", "krl", "KRYLL"),
    DFORCE("dforce-token", "df", "dForce"),
    LAW_BLOCKS("law-blocks", "lbt", "Law Blocks"),
    HOPR("hopr", "hopr", "HOPR"),
    REBEL_BOTS("rebel-bots", "rbls", "Rebel Bots"),
    DEXLAB("dexlab", "dxl", "Dexlab"),
    KAVA_SWAP("kava-swap", "swp", "Kava Swap"),
    FEG("feg-token", "feg", "FEG"),
    APOLLOX("apollox-2", "apx", "ApolloX"),
    RAI_REFLEX_INDEX("rai", "rai", "Rai Reflex Index"),
    JET("jet", "jet", "JET"),
    PEERCOIN("peercoin", "ppc", "Peercoin"),
    SIX_NETWORK("six-network", "six", "SIX Network"),
    LOCKTRIP("lockchain", "loc", "LockTrip"),
    DERACE("derace", "derc", "DeRace"),
    ELECTRA_PROTOCOL("electra-protocol", "xep", "Electra Protocol"),
    APESWAP("apeswap-finance", "banana", "ApeSwap"),
    BOSAGORA("bosagora", "boa", "BOSAGORA"),
    TOKPIE("tokpie", "tkp", "TOKPIE"),
    INVERSE_FINANCE("inverse-finance", "inv", "Inverse Finance"),
    R_CRYPTOCURRENCY_MOONS("moon", "moon", "r/CryptoCurrency Moons"),
    APEX("apex-token-2", "apex", "ApeX"),
    ALKIMI("alkimi", "$ads", "Alkimi"),
    JUVENTUS_FAN_TOKEN("juventus-fan-token", "juv", "Juventus Fan Token"),
    AC_MILAN_FAN_TOKEN("ac-milan-fan-token", "acm", "AC Milan Fan Token"),
    NIMIQ("nimiq-2", "nim", "Nimiq"),
    INSTADAPP("instadapp", "inst", "Instadapp"),
    MEDIA_LICENSING("media-licensing-token", "mlt", "Media Licensing"),
    BITCOIN_2("bitcoin-2", "btc2", "Bitcoin 2"),
    OBYTE("byteball", "gbyte", "Obyte"),
    JPEG_D("jpeg-d", "jpeg", "JPEG'd"),
    ASSETMANTLE("assetmantle", "mntl", "AssetMantle"),
    VERTCOIN("vertcoin", "vtc", "Vertcoin"),
    META_APES_PEEL("meta-apes-peel", "peel", "Meta Apes PEEL"),
    VERAONE("veraone", "vro", "VeraOne"),
    SPOOKYSWAP("spookyswap", "boo", "Spookyswap"),
    BADGER_INTEREST_BEARING_BITCOIN("interest-bearing-bitcoin", "ibbtc", "Badger Interest Bearing Bitcoin"),
    SIPHER("sipher", "sipher", "Sipher"),
    ARCBLOCK("arcblock", "abt", "Arcblock"),
    OXEN("loki-network", "oxen", "Oxen"),
    OAX("openanx", "oax", "OAX"),
    LUFFY("luffy-inu", "luffy", "Luffy"),
    CRYPTO_GLADIATOR_SHARDS("crypto-gladiator-shards", "cgs", "Crypto Gladiator Shards"),
    OPULOUS("opulous", "opul", "Opulous"),
    SBTC("sbtc", "sbtc", "sBTC"),
    DEXTOOLS("dextools", "dext", "DexTools"),
    MIRRORED_ETHER("mirrored-ether", "meth", "Mirrored Ether"),
    SIDESHIFT("sideshift-token", "xai", "SideShift"),
    PNETWORK("pnetwork", "pnt", "pNetwork"),
    APOLLO("apollo", "apl", "Apollo"),
    DIAMOND("diamond", "dmd", "Diamond"),
    SONM("sonm", "snm", "SONM"),
    E_MONEY("e-money", "ngm", "e-Money"),
    CRYPTEX_FINANCE("cryptex-finance", "ctx", "Cryptex Finance"),
    MOVIEBLOC("moviebloc", "mbl", "MovieBloc"),
    DORA_FACTORY("dora-factory", "dora", "Dora Factory"),
    VIBERATE("viberate", "vib", "Viberate"),
    INDEX_COOP_ETH_2X_FLEXIBLE_LEVERAGE_INDEX("eth-2x-flexible-leverage-index", "eth2x-fli", "Index Coop - ETH 2x Flexible Leverage Index"),
    GIFTO("gifto", "gto", "Gifto"),
    VIRES_FINANCE("vires-finance", "vires", "Vires Finance"),
    ZKSPACE("zkspace", "zks", "ZKSpace"),
    INTEREST_COMPOUNDING_ETH_INDEX("interest-compounding-eth-index", "iceth", "Interest Compounding ETH Index"),
    PORTUGAL_NATIONAL_TEAM_FAN_TOKEN("portugal-national-team-fan-token", "por", "Portugal National Team Fan Token"),
    MITHRIL("mithril", "mith", "Mithril"),
    RSS3("rss3", "rss3", "RSS3"),
    X2Y2("x2y2", "x2y2", "X2Y2"),
    SCPRIME("siaprime-coin", "scp", "ScPrime"),
    AURORY("aurory", "aury", "Aurory"),
    ZIPMEX("zipmex-token", "zmt", "Zipmex"),
    XFUND("xfund", "xfund", "xFund"),
    HOGE_FINANCE("hoge-finance", "hoge", "Hoge Finance"),
    PEAKDEFI("marketpeak", "peak", "PEAKDEFI"),
    QUANTSTAMP("quantstamp", "qsp", "Quantstamp"),
    NOMINEX("nominex", "nmx", "Nominex"),
    YUAN_CHAIN_COIN("yuan-chain-coin", "ycc", "Yuan Chain Coin"),
    CARBON_PROTOCOL("switcheo", "swth", "Carbon Protocol"),
    TECTONIC("tectonic", "tonic", "Tectonic"),
    REDDCOIN("reddcoin", "rdd", "Reddcoin"),
    WXT_TOKEN("wirex", "wxt", "WXT Token"),
    LOSSLESS("lossless", "lss", "Lossless"),
    QUANTUM_RESISTANT_LEDGER("quantum-resistant-ledger", "qrl", "Quantum Resistant Ledger"),
    VIDT_DATALINK("v-id-blockchain", "vidt", "VIDT Datalink"),
    SPORT_AND_LEISURE("sport-and-leisure", "snl", "Sport and Leisure"),
    INARI("inari", "inari", "Inari"),
    DIGIXDAO("digixdao", "dgd", "DigixDAO"),
    DFX_FINANCE("dfx-finance", "dfx", "DFX Finance"),
    RHINO_FI("rhinofi", "dvf", "Rhino.fi"),
    LOVECHAIN("lovechain", "lov", "LoveChain"),
    NUM_TOKEN("numbers-protocol", "num", "NUM Token"),
    MAPS("maps", "maps", "MAPS"),
    PETALS("petals", "pts", "Petals"),
    GARI_NETWORK("gari-network", "gari", "Gari Network"),
    PANGOLIN("pangolin", "png", "Pangolin"),
    INVICTUS("invictus", "in", "Invictus"),
    THE_WINKYVERSE("the-winkyverse", "wnk", "The Winkyverse"),
    STARCOIN("starcoin", "stc", "Starcoin"),
    CRUST_NETWORK("crust-network", "cru", "Crust Network"),
    WONDERLAND("wonderland", "time", "Wonderland"),
    REFLEXER_UNGOVERNANCE("reflexer-ungovernance-token", "flx", "Reflexer Ungovernance"),
    INFINITECOIN("infinitecoin", "ifc", "Infinitecoin"),
    THORSWAP("thorswap", "thor", "THORSwap"),
    INTER_MILAN_FAN_TOKEN("inter-milan-fan-token", "inter", "Inter Milan Fan Token"),
    INDEX_COOPERATIVE("index-cooperative", "index", "Index Cooperative"),
    SPAIN_NATIONAL_FOOTBALL_TEAM_FAN_TOKEN("spain-national-fan-token", "snft", "Spain National Football Team Fan Token"),
    WHALE("whale", "whale", "WHALE"),
    BITCOIN_PRO("bitcoin-pro", "btcp", "Bitcoin Pro"),
    OMAX("omax-token", "omax", "Omax"),
    MUTE("mute", "mute", "Mute"),
    PUNDI_X_OLD("pundi-x", "npxs", "Pundi X [OLD]"),
    OCTUS_BRIDGE("octus-bridge", "bridge", "Octus Bridge"),
    SWFTCOIN("swftcoin", "swftc", "SWFTCOIN"),
    KRIPTO("kripto", "kripto", "Kripto"),
    VEED("veed", "veed", "VEED"),
    ZENON("zenon", "znn", "Zenon"),
    XANA("xana", "xeta", "XANA"),
    BATTLE_INFINITY("battle-infinity", "ibat", "Battle Infinity"),
    ATLETICO_MADRID_FAN_TOKEN("atletico-madrid", "atm", "Atletico Madrid Fan Token"),
    COSPLAY_TOKEN("cosplay-token-2", "cot", "Cosplay Token"),
    SEUR("seur", "seur", "sEUR"),
    DIGITALBITS("digitalbits", "xdb", "DigitalBits"),
    RUPIAH("rupiah-token", "idrt", "Rupiah"),
    CAKE_MONSTER("cake-monster", "monsta", "Cake Monster"),
    TABOO("taboo-token", "taboo", "Taboo"),
    ADAPPTER("adappter-token", "adp", "Adappter"),
    FORTUBE("force-protocol", "for", "ForTube"),
    SYLO("sylo", "sylo", "Sylo"),
    OXYGEN("oxygen", "oxy", "Oxygen"),
    COUNTERPARTY("counterparty", "xcp", "Counterparty"),
    PARAGONSDAO("paragonsdao", "pdt", "ParagonsDAO"),
    BEPRO_NETWORK("bepro-network", "bepro", "BEPRO Network"),
    POPCORN("popcorn", "pop", "Popcorn"),
    PARASWAP("paraswap", "psp", "ParaSwap"),
    ARIVA("ariva", "arv", "Ariva"),
    CREAM("cream-2", "cream", "Cream"),
    DOHRNII("dohrnii", "dhn", "Dohrnii"),
    CRYPTERIUM("crypterium", "crpt", "Crypterium"),
    BTU_PROTOCOL("btu-protocol", "btu", "BTU Protocol"),
    WEWAY("weway", "wwy", "WeWay"),
    ARSENAL_FAN_TOKEN("arsenal-fan-token", "afc", "Arsenal Fan Token"),
    KASTA("kasta", "kasta", "Kasta"),
    ALTURA("altura", "alu", "Altura"),
    PHONON_DAO("phonon-dao", "phonon", "Phonon DAO"),
    ENERGI("energi", "nrg", "Energi"),
    GELATO("gelato", "gel", "Gelato"),
    ATLAS_USV("atlas-usv", "usv", "Atlas USV"),
    QI_DAO("qi-dao", "qi", "Qi Dao"),
    GENOPETS("genopets", "gene", "Genopets"),
    GAMIUM("gamium", "gmm", "Gamium"),
    BSCPAD("bscpad", "bscpad", "BSCPAD"),
    DEGO_FINANCE("dego-finance", "dego", "Dego Finance"),
    STAR_ATLAS("star-atlas", "atlas", "Star Atlas"),
    GRIDPLUS_OLD("grid", "grid", "GridPlus [OLD]"),
    ZERO_CHAIN("0chain", "zcn", "0chain"),
    POWERPOOL_CONCENTRATED_VOTING_POWER("concentrated-voting-power", "cvp", "PowerPool Concentrated Voting Power"),
    COW_PROTOCOL("cow-protocol", "cow", "CoW Protocol"),
    EDEN("eden", "eden", "EDEN"),
    REVOLUTION_POPULI("revolution-populi", "rvp", "Revolution Populi"),
    FOAM("foam-protocol", "foam", "FOAM"),
    WALKEN("walken", "wlkn", "Walken"),
    THREE_X_LONG_ETHEREUM_TOKEN("3x-long-ethereum-token", "ethbull", "3X Long Ethereum Token"),
    NETVRK("netvrk", "ntvrk", "Netvrk"),
    REVV("revv", "revv", "REVV"),
    VITA_INU("vita-inu", "vinu", "Vita Inu"),
    POLKADEX("polkadex", "pdex", "Polkadex"),
    OPENDAO("opendao", "sos", "OpenDAO"),
    MYSTERIUM("mysterium", "myst", "Mysterium"),
    SWAPXI("swapxi-token", "swapxi", "SwapXI"),
    POCKETCOIN("pocketcoin", "pkoin", "Pocketcoin"),
    TOMB("tomb", "tomb", "Tomb"),
    NEW_BITSHARES("new-bitshares", "nbs", "New BitShares"),
    RECEIVE_ACCESS_ECOSYSTEM("rae-token", "rae", "Receive Access Ecosystem"),
    CHAINGE_FINANCE("chainge-finance", "chng", "Chainge Finance"),
    UNDEAD_BLOCKS("undead-blocks", "undead", "Undead Blocks"),
    POINTPAY("pointpay", "pxp", "PointPay"),
    DVISION_NETWORK("dvision-network", "dvi", "Dvision Network"),
    SOVRYN("sovryn", "sov", "Sovryn"),
    CORNUCOPIAS("cornucopias", "copi", "Cornucopias"),
    APM_COIN("apm-coin", "apm", "apM Coin"),
    DACXI("dacxi", "dacxi", "Dacxi"),
    TERNOA("coin-capsule", "caps", "Ternoa"),
    WALTONCHAIN("waltonchain", "wtc", "Waltonchain"),
    FLAMENGO_FAN_TOKEN("flamengo-fan-token", "mengo", "Flamengo Fan Token"),
    GALATASARAY_FAN_TOKEN("galatasaray-fan-token", "gal", "Galatasaray Fan Token"),
    BOSTROM("bostrom", "boot", "Bostrom"),
    HIBLOCKS("hiblocks", "hibs", "Hiblocks"),
    MMFINANCE_CRONOS("mmfinance", "mmf", "MMFinance (Cronos)"),
    GOCHAIN("gochain", "go", "GoChain"),
    UXD_PROTOCOL("uxd-protocol-token", "uxp", "UXD Protocol"),
    SATT("satt", "satt", "SaTT"),
    SIFCHAIN("sifchain", "erowan", "Sifchain"),
    PROJECT_SEED_SHILL("shill-token", "shill", "Project SEED SHILL"),
    CROWDSWAP("crowdswap", "crowd", "CrowdSwap"),
    CRYPTO_LEGIONS_V3("crypto-legions-v3", "blv3", "Crypto Legions V3"),
    BAO_FINANCE("bao-finance", "bao", "Bao Finance"),
    UNICRYPT("unicrypt-2", "uncx", "UniCrypt"),
    AVALAUNCH("avalaunch", "xava", "Avalaunch"),
    WASDER("wasder", "was", "Wasder"),
    RUBIC("rubic", "rbc", "Rubic"),
    ELYSIA("elysia", "el", "ELYSIA"),
    PALLAPAY("pallapay", "palla", "Pallapay"),
    CWBTC("compound-wrapped-btc", "cwbtc", "cWBTC"),
    STORX("storx", "srx", "StorX"),
    HOTBIT("hotbit-token", "htb", "Hotbit"),
    VIVID_LABS("videocoin", "vid", "Vivid Labs"),
    NFTX("nftx", "nftx", "NFTX"),
    SCALLOP("scallop", "sclp", "Scallop"),
    AURUSDEFI("auruscoin", "awx", "AurusDeFi"),
    VOXIES("voxies", "voxel", "Voxies"),
    GULFCOIN("gulfcoin-2", "gulf", "GulfCoin"),
    PANTHER_PROTOCOL("panther", "zkp", "Panther Protocol"),
    TORNADO_CASH("tornado-cash", "torn", "Tornado Cash"),
    SHYFT_NETWORK("shyft-network-2", "shft", "Shyft Network"),
    XELS("xels", "xels", "XELS"),
    EVEREST("everid", "id", "Everest"),
    LINGOSE("lingose", "ling", "Lingose"),
    SUKU("suku", "suku", "SUKU"),
    DOLLARS("dollars", "usdx", "Dollars"),
    NMKR("nft-maker", "$nmkr", "NMKR"),
    HEGIC("hegic", "hegic", "Hegic"),
    SOLANIUM("solanium", "slim", "Solanium"),
    ARBISMART("arbismart-token", "rbis", "ArbiSmart"),
    AUROX("urus-token", "urus", "Aurox"),
    TRUSTPAD("trustpad", "tpad", "TrustPad"),
    INFINITY_PAD("infinity-pad-2", "ipad", "Infinity PAD"),
    METAVERSE_NETWORK_PIONEER("metaverse-network-pioneer", "neer", "Metaverse.Network Pioneer"),
    QUADRANT_PROTOCOL("quadrant-protocol", "equad", "Quadrant Protocol"),
    HACKEN_HAI("hackenai", "hai", "Hacken HAI"),
    DIMECOIN("dimecoin", "dime", "Dimecoin"),
    MUSE_DAO("muse-2", "muse", "Muse DAO"),
    COLA("cola-token", "cola", "Cola"),
    MIMO_GOVERNANCE("mimo-parallel-governance-token", "mimo", "Mimo Governance"),
    SOCEAN_STAKED_SOL("socean-staked-sol", "scnsol", "Socean Staked Sol"),
    STAR_ATLAS_DAO("star-atlas-dao", "polis", "Star Atlas DAO"),
    THE_DOGE_NFT("the-doge-nft", "dog", "The Doge NFT"),
    XDEFI("xdefi", "xdefi", "XDEFI"),
    ENJINSTARTER("enjinstarter", "ejs", "Enjinstarter"),
    JUPITER("jupiter", "jup", "Jupiter"),
    SWASH("swash", "swash", "Swash");

    public final String id;
    public final String symbol;
    public final String name;

    private static final List<String> ID_LIST = new ArrayList<>();

    static {
        for (ECryptocurrency c : values()) {
            ID_LIST.add(c.id);
        }
    }

    ECryptocurrency(String id, String symbol, String name) {
        this.id = id;
        this.symbol = symbol;
        this.name = name;
    }

    public static ECryptocurrency getById(String id) {
        for (ECryptocurrency c : values()) {
            if (c.id.equals(id)) {
                return c;
            }
        }
        return null;
    }

    public static List<String> getIdList() {
        return ID_LIST;
    }

}